### ISSUE TITLE
Await  error

### ISSUE THREAD

**Issue by Tashaun272** [scalic/scalic-selfbot#4]
It keeps saying  File "3Hunna.py", line 1637
    await asyncio.sleep(8) 
    ^
SyntaxError: 'await' outside function how do i fix this

**Comment by kieronia** [comment]
I didn't make anything named 3hunna, not sure what you're having errors with

**Comment by Hy6x** [comment]
from halo import Halo
ModuleNotFoundError: No module named 'halo'

**Comment by Tashaun272** [comment]
File "Scalic.py", line 539
    await asyncio.sleep(int(deleteaftertime))
    ^
SyntaxError: 'await' outside function why does it keep saying this?
