### ISSUE TITLE
win10toast import problem

### ISSUE THREAD

**Issue by babbaoi** [scalic/scalic-selfbot#6]
it always displays the error module not found win10toast i even typed "pip install win10toast" but it was still displaying the same erorr

**Comment by dauntIess** [comment]
## Win10Toast Issue
In the source code, remove the following lines:
### Lines 94~98
![ss_da](https://i.vgy.me/zop4FR.png)
### Lines 2726~2731
![ss_da1](https://i.vgy.me/IJdPNY.png)
